apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.headlessService }}
  labels:
    component: activemq-broker
    {{ include "standardLabels" . | indent 4 }}
spec:
  ports:
  - port: 61616
  clusterIP: None
  selector:
    app: {{ .Values.global.applicationName }}
    component: activemq-broker
    release: {{ .Release.Name | quote }}